# Generated by Django 3.2.21 on 2023-09-25 15:22

from django.db import migrations, models
import task_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=task_app.models.Taskimg)),
                ('option_priority', models.CharField(choices=[('Low', 'Low'), ('Media', 'Media'), ('High', 'High')], max_length=100)),
                ('task_complete', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('create_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'TaskModel',
                'verbose_name_plural': 'TaskModel',
            },
        ),
    ]
